esphome:
  includes:
    - cc1101.h
  libraries:
      - SPI
      - "SmartRC-CC1101-Driver-Lib"

  name: CC1101 Garage
  friendly_name: garage


esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

ota:
  - platform: esphome
    password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "CC1101 Garage"
    password: !secret wifi_password

captive_portal:

sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new CC1101(
        // SeeedStudio Xiao ESP32 s3 example use GPIO numbers, not DX
        8,// SCK
        4,// MISO
        9,// MOSI
        43,// CSN
        44,// GDO0
        433.92,// freq_in_mhz
        2, // set modulation mode. 0 = 2-FSK, 1 = GFSK, 2 = ASK/OOK, 3 = 4-FSK, 4 = MSK.
        id(transmitter) // id of remote_transmitter
      );
      App.register_component(my_sensor);
      return {my_sensor};
    sensors:
      id: transceiver
      internal: true

remote_transmitter:
  id: transmitter
  pin: GPIO44 # This is GDO0 with GPIOXX Naming Scheme
  carrier_duty_percent: 100%

switch: # instead of button, Matterbridge as of this date does not suppont buttons, neither google home
  - platform: template
    id: garage_gate
    name: "garaje"
    icon: "mdi:gate"
    turn_on_action:
        - lambda: get_cc1101(transceiver).beginTransmission();
        - remote_transmitter.transmit_raw:
            # prettier-ignore
            # encoding in binary is better for Clemsa than encoding by timing, for Clemsa MV12 each bit is 60 - 65 microseconds
              code: [-2880, 60, -60, 60, -60, 60, -60, 60, -60, 60, -60, 60, -60, 60, -60, 60, -60, 60, -60, 60, -4860]
              repeat:
                # repeating the signal so it does not fail
                times: 6
                wait_time: 8ms
        - delay: 3s
        - switch.turn_off: garage_gate
    turn_off_action: # make the switch act as a push button
        - delay: 1s
    
              
